[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
demoprogram = "8hgoWMEXWCPLg7kPMx6T3Ykyukqtyk71PRvUmrhqpM61"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/chiragjani/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
